#!/bin/bash

set -eu -o pipefail

release_dir="$( cd "$( dirname "$0" )" && cd ../.. && pwd )"
workspace_dir="$( cd "${release_dir}" && cd .. && pwd )"

BUILT_RESOURCE=$PWD/built-resource

export GOPATH=$PWD/gopath
export PATH=$PWD/gopath/bin:$PATH

cd $(dirname $0)/../..

go get github.com/concourse/s3-resource

go build -o ./assets/check ./cmd/check
go build -o ./assets/in ./cmd/in
go build -o ./assets/out ./cmd/out

cp -a ./* ${BUILT_RESOURCE}/

cp "${workspace_dir}/${DOCKERFILE_DIR}/Dockerfile" ${BUILT_RESOURCE}/
