---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/static-golang}

inputs:
  - name: resource-src
    path: gopath/src/github.com/concourse/resource-src

outputs:
  - name: built-resource

run:
  path: gopath/src/github.com/concourse/resource-src/ci/scripts/build-artifacts

params:
  DOCKERFILE_DIR: "resource-src/dockerfiles/alpine/"
